from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request payload for sending a chat message to the assistant."""
    message: str = Field(..., description="User message prompt", example="What is the weather in Tokyo?")
    thread_id: Optional[str] = Field("default_thread", description="Unique session thread ID for conversation memory", example="user-session-101")


class ChatResponse(BaseModel):
    """Response payload returned by the assistant."""
    response: str = Field(..., description="Final text answer generated by the assistant")
    tool_calls: List[Dict[str, Any]] = Field(default_factory=list, description="List of tools invoked during reasoning loop")
    thread_id: str = Field(..., description="Active session thread ID")


class HistoryResponse(BaseModel):
    """Response payload containing conversation thread history."""
    thread_id: str = Field(..., description="Session thread ID")
    history: List[Dict[str, str]] = Field(..., description="Chronological message history list")


class HealthResponse(BaseModel):
    """Response payload for system health check."""
    status: str = Field("healthy", example="healthy")
    model: str = Field(..., example="gemini-2.5-flash")
    api_key_configured: bool = Field(..., example=True)
